### ISSUE TITLE
the prime solution seems familiar 

### ISSUE THREAD

**Issue by rsharifnasab** [iotahacodes/soallpeach#1]
hey bro, we are not competitor, but just friends,
but if you copy the whole code, just think about **starring** the [source repository](https://github.com/rsharifnasab/soallpeach/blob/master/prime/a.c).
:)

**Comment by iotahacodes** [comment]
you're totally right, i'm so sorry about that, this was just a temporary thing, as you can see i used your code to make sure my Dockerfile works OK and i kept my own code to get back on it later, but there is no excuse, and once again i'm Sorry

**Comment by iotahacodes** [comment]
and also i putted some explanations in the code, as the way for some kind of apology:
https://github.com/iotahacodes/soallpeach/blob/master/prime/src/main.c

**Comment by rsharifnasab** [comment]
hey dude, absoloutely no problem. we are open source developers, i just wanted that star.
you are so kind and moral, I'm new to docker too and its really hard to wait 1 hour for every test.

best wishes, roozbeh
